version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3007:3007"
    links:
      - db #links to db service
    volumes:
      - .:/hackbnb/app
    depends_on:
      - db
      
  db:
    image: mongo
